import type {
  PhraseDefinition,
  LessonDefinition,
  LessonStepDefinition,
  ReviewSourceLink,
  PatternSlotOption,
} from './lesson-domain-types'

export const MVP_PHRASES: PhraseDefinition[] = [
  {
    id: 'wake_up__morning_greeting__core_phrase__good_morning',
    sceneId: 'wake_up',
    microSituationId: 'wake_up__morning_greeting',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'core_phrase',
    text: 'Good morning.',
    translation: 'おはよう。',
    notes: null,
    difficulty: 1,
    tags: ['greeting', 'morning'],
    audioText: 'Good morning.',
    isCore: true,
  },
  {
    id: 'wake_up__morning_greeting__scene_expression__slept_well',
    sceneId: 'wake_up',
    microSituationId: 'wake_up__morning_greeting',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'scene_expression',
    text: 'I slept well.',
    translation: 'よく眠れました。',
    notes: null,
    difficulty: 1,
    tags: ['sleep', 'response'],
    audioText: 'I slept well.',
    isCore: true,
  },
  {
    id: 'breakfast__say_what_you_ate__core_phrase__had_eggs',
    sceneId: 'breakfast',
    microSituationId: 'breakfast__say_what_you_ate',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'core_phrase',
    text: 'I had eggs and toast.',
    translation: '卵とトーストを食べました。',
    notes: null,
    difficulty: 1,
    tags: ['breakfast', 'food'],
    audioText: 'I had eggs and toast.',
    isCore: true,
  },
  {
    id: 'breakfast__say_what_you_ate__pattern__i_had',
    sceneId: 'breakfast',
    microSituationId: 'breakfast__say_what_you_ate',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'pattern',
    text: 'I had [food].',
    translation: '〜を食べました。',
    notes: null,
    difficulty: 1,
    tags: ['pattern', 'breakfast'],
    audioText: 'I had [food].',
    isCore: false,
  },
  {
    id: 'shopping__ask_price__core_phrase__how_much',
    sceneId: 'shopping',
    microSituationId: 'shopping__ask_price',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'core_phrase',
    text: 'How much is this?',
    translation: 'これはいくらですか。',
    notes: null,
    difficulty: 1,
    tags: ['shopping', 'price'],
    audioText: 'How much is this?',
    isCore: true,
  },
  {
    id: 'shopping__ask_price__scene_expression__dollars',
    sceneId: 'shopping',
    microSituationId: 'shopping__ask_price',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'scene_expression',
    text: "It's five dollars.",
    translation: '5ドルです。',
    notes: null,
    difficulty: 1,
    tags: ['price', 'response'],
    audioText: "It's five dollars.",
    isCore: true,
  },
  {
    id: 'restaurant__order_food__core_phrase__id_like',
    sceneId: 'restaurant',
    microSituationId: 'restaurant__order_food',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'core_phrase',
    text: "I'd like the salad, please.",
    translation: 'サラダをください。',
    notes: null,
    difficulty: 2,
    tags: ['restaurant', 'order'],
    audioText: "I'd like the salad, please.",
    isCore: true,
  },
  {
    id: 'restaurant__order_food__pattern__id_like',
    sceneId: 'restaurant',
    microSituationId: 'restaurant__order_food',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'pattern',
    text: "I'd like [item], please.",
    translation: '〜をください。',
    notes: null,
    difficulty: 2,
    tags: ['pattern', 'order'],
    audioText: "I'd like [item], please.",
    isCore: false,
  },
  {
    id: 'meet_friend__greeting__core_phrase__hey',
    sceneId: 'meet_friend',
    microSituationId: 'meet_friend__greeting',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'core_phrase',
    text: 'Hey! Good to see you.',
    translation: 'やあ、会えて嬉しい。',
    notes: null,
    difficulty: 1,
    tags: ['greeting', 'friend'],
    audioText: 'Hey! Good to see you.',
    isCore: true,
  },
  {
    id: 'meet_friend__greeting__guided_answer__same_here',
    sceneId: 'meet_friend',
    microSituationId: 'meet_friend__greeting',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'guided_answer',
    text: 'Same here!',
    translation: 'こちらこそ。',
    notes: null,
    difficulty: 1,
    tags: ['response', 'casual'],
    audioText: 'Same here!',
    isCore: false,
  },
  {
    id: 'office_greeting__greet_coworkers__core_phrase__good_morning',
    sceneId: 'office_greeting',
    microSituationId: 'office_greeting__greet_coworkers',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'core_phrase',
    text: 'Good morning. How are you?',
    translation: 'おはようございます。お元気ですか。',
    notes: null,
    difficulty: 2,
    tags: ['greeting', 'work'],
    audioText: 'Good morning. How are you?',
    isCore: true,
  },
  {
    id: 'office_greeting__greet_coworkers__guided_answer__doing_well',
    sceneId: 'office_greeting',
    microSituationId: 'office_greeting__greet_coworkers',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'guided_answer',
    text: "I'm doing well, thanks.",
    translation: '元気です、ありがとう。',
    notes: null,
    difficulty: 2,
    tags: ['response', 'work'],
    audioText: "I'm doing well, thanks.",
    isCore: false,
  },
  {
    id: 'first_date__greeting__core_phrase__nice_to_meet',
    sceneId: 'first_date',
    microSituationId: 'first_date__greeting',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'core_phrase',
    text: "It's nice to meet you.",
    translation: 'お会いできて嬉しいです。',
    notes: null,
    difficulty: 2,
    tags: ['greeting', 'date'],
    audioText: "It's nice to meet you.",
    isCore: true,
  },
  {
    id: 'first_date__greeting__free_conversation_seed__you_too',
    sceneId: 'first_date',
    microSituationId: 'first_date__greeting',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'free_conversation_seed',
    text: "You too! I've been looking forward to this.",
    translation: 'こちらこそ。楽しみにしていました。',
    notes: null,
    difficulty: 2,
    tags: ['date', 'warm'],
    audioText: "You too! I've been looking forward to this.",
    isCore: false,
  },
  {
    id: 'describe_symptom__what_hurts__core_phrase__headache',
    sceneId: 'describe_symptom',
    microSituationId: 'describe_symptom__what_hurts',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'core_phrase',
    text: "I have a headache.",
    translation: '頭が痛いです。',
    notes: null,
    difficulty: 2,
    tags: ['symptom', 'health'],
    audioText: "I have a headache.",
    isCore: true,
  },
  {
    id: 'describe_symptom__what_hurts__pattern__i_have_a',
    sceneId: 'describe_symptom',
    microSituationId: 'describe_symptom__what_hurts',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    kind: 'pattern',
    text: "I have a [symptom].",
    translation: '〜が痛いです。／〜があります。',
    notes: null,
    difficulty: 2,
    tags: ['pattern', 'symptom'],
    audioText: "I have a [symptom].",
    isCore: false,
  },
]

export const MVP_LESSONS: LessonDefinition[] = [
  {
    id: 'wake_up__morning_greeting__lesson',
    sceneId: 'wake_up',
    microSituationId: 'wake_up__morning_greeting',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    title: '朝の挨拶',
    description: '朝起きたときの挨拶',
    goal: '朝の挨拶ができる',
    difficulty: 1,
    estimatedMinutes: 4,
    stepTypes: ['listen', 'repeat', 'pattern', 'guided', 'free_conversation'],
    steps: [
      {
        id: 'wake_up__morning_greeting__lesson__step_1',
        lessonId: 'wake_up__morning_greeting__lesson',
        orderIndex: 1,
        type: 'listen',
        prompt: 'Listen to the phrase.',
        instruction: 'フレーズを聞いてください。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: 'wake_up__morning_greeting__core_phrase__good_morning',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'wake_up__morning_greeting__lesson__step_2',
        lessonId: 'wake_up__morning_greeting__lesson',
        orderIndex: 2,
        type: 'repeat',
        prompt: 'Say: Good morning.',
        instruction: '言ってみましょう：Good morning.',
        hint: 'おはよう、です。',
        exampleAnswer: null,
        expectedAnswer: 'Good morning.',
        basePhraseId: 'wake_up__morning_greeting__core_phrase__good_morning',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['wake_up__morning_greeting__core_phrase__good_morning'],
        aiRole: null,
      },
      {
        id: 'wake_up__morning_greeting__lesson__step_3',
        lessonId: 'wake_up__morning_greeting__lesson',
        orderIndex: 3,
        type: 'pattern',
        prompt: 'Say how you feel: I feel ___.',
        instruction: '気持ちを言いましょう：I feel ___.',
        hint: 'tired / great / okay のどれかで。',
        exampleAnswer: 'I feel great.',
        expectedAnswer: 'I feel [adjective].',
        basePhraseId: null,
        patternSlotName: 'adjective',
        patternSlotOptions: [
          { value: 'tired', label: '疲れた' },
          { value: 'great', label: '元気' },
          { value: 'okay', label: 'まあまあ' },
        ],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'wake_up__morning_greeting__lesson__step_4',
        lessonId: 'wake_up__morning_greeting__lesson',
        orderIndex: 4,
        type: 'guided',
        prompt: 'Your roommate says: How did you sleep? Answer.',
        instruction: 'ルームメイトが「よく眠れた？」と聞きました。答えてください。',
        hint: 'I slept well. が使えます。',
        exampleAnswer: 'I slept well.',
        expectedAnswer: 'I slept well.',
        basePhraseId: 'wake_up__morning_greeting__scene_expression__slept_well',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['wake_up__morning_greeting__scene_expression__slept_well'],
        aiRole: 'roommate',
      },
      {
        id: 'wake_up__morning_greeting__lesson__step_5',
        lessonId: 'wake_up__morning_greeting__lesson',
        orderIndex: 5,
        type: 'free_conversation',
        prompt: 'Have a short morning exchange with your roommate.',
        instruction: 'ルームメイトと朝の短いやりとりをしましょう。',
        hint: '挨拶と一言でOK。',
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: 'roommate',
      },
    ],
    phraseIds: [
      'wake_up__morning_greeting__core_phrase__good_morning',
      'wake_up__morning_greeting__scene_expression__slept_well',
    ],
    isReviewLesson: false,
    isActive: true,
  },
  {
    id: 'breakfast__say_what_you_ate__lesson',
    sceneId: 'breakfast',
    microSituationId: 'breakfast__say_what_you_ate',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    title: '食べたものを言う',
    description: '何を食べたか伝える',
    goal: '食べた内容を伝えられる',
    difficulty: 1,
    estimatedMinutes: 4,
    stepTypes: ['listen', 'repeat', 'pattern', 'guided', 'free_conversation'],
    steps: [
      {
        id: 'breakfast__say_what_you_ate__lesson__step_1',
        lessonId: 'breakfast__say_what_you_ate__lesson',
        orderIndex: 1,
        type: 'listen',
        prompt: 'Listen to the phrase.',
        instruction: 'フレーズを聞いてください。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: 'breakfast__say_what_you_ate__core_phrase__had_eggs',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'breakfast__say_what_you_ate__lesson__step_2',
        lessonId: 'breakfast__say_what_you_ate__lesson',
        orderIndex: 2,
        type: 'repeat',
        prompt: 'Say: I had eggs and toast.',
        instruction: '言ってみましょう。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: 'I had eggs and toast.',
        basePhraseId: 'breakfast__say_what_you_ate__core_phrase__had_eggs',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['breakfast__say_what_you_ate__core_phrase__had_eggs'],
        aiRole: null,
      },
      {
        id: 'breakfast__say_what_you_ate__lesson__step_3',
        lessonId: 'breakfast__say_what_you_ate__lesson',
        orderIndex: 3,
        type: 'pattern',
        prompt: 'Say what you had: I had ___.',
        instruction: '食べたものを言いましょう：I had ___.',
        hint: 'cereal / coffee / yogurt など。',
        exampleAnswer: 'I had cereal.',
        expectedAnswer: 'I had [food].',
        basePhraseId: 'breakfast__say_what_you_ate__pattern__i_had',
        patternSlotName: 'food',
        patternSlotOptions: [
          { value: 'cereal', label: 'シリアル' },
          { value: 'coffee', label: 'コーヒー' },
          { value: 'yogurt', label: 'ヨーグルト' },
          { value: 'toast', label: 'トースト' },
        ],
        reviewSourcePhraseIds: ['breakfast__say_what_you_ate__pattern__i_had'],
        aiRole: null,
      },
      {
        id: 'breakfast__say_what_you_ate__lesson__step_4',
        lessonId: 'breakfast__say_what_you_ate__lesson',
        orderIndex: 4,
        type: 'guided',
        prompt: 'Someone asks: What did you have for breakfast? Answer.',
        instruction: '「朝食に何を食べた？」と聞かれました。答えてください。',
        hint: null,
        exampleAnswer: 'I had eggs and toast.',
        expectedAnswer: 'I had [food].',
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['breakfast__say_what_you_ate__core_phrase__had_eggs'],
        aiRole: null,
      },
      {
        id: 'breakfast__say_what_you_ate__lesson__step_5',
        lessonId: 'breakfast__say_what_you_ate__lesson',
        orderIndex: 5,
        type: 'free_conversation',
        prompt: 'Tell your family or friend what you had for breakfast.',
        instruction: '家族や友達に朝食の内容を話しましょう。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: 'family',
      },
    ],
    phraseIds: [
      'breakfast__say_what_you_ate__core_phrase__had_eggs',
      'breakfast__say_what_you_ate__pattern__i_had',
    ],
    isReviewLesson: false,
    isActive: true,
  },
  {
    id: 'shopping__ask_price__lesson',
    sceneId: 'shopping',
    microSituationId: 'shopping__ask_price',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    title: '値段を聞く',
    description: '商品の値段を聞く',
    goal: '値段を聞いて答えられる',
    difficulty: 1,
    estimatedMinutes: 4,
    stepTypes: ['listen', 'repeat', 'pattern', 'guided', 'free_conversation'],
    steps: [
      {
        id: 'shopping__ask_price__lesson__step_1',
        lessonId: 'shopping__ask_price__lesson',
        orderIndex: 1,
        type: 'listen',
        prompt: 'Listen to the question.',
        instruction: '質問を聞いてください。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: 'shopping__ask_price__core_phrase__how_much',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'shopping__ask_price__lesson__step_2',
        lessonId: 'shopping__ask_price__lesson',
        orderIndex: 2,
        type: 'repeat',
        prompt: 'Say: How much is this?',
        instruction: '言ってみましょう。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: 'How much is this?',
        basePhraseId: 'shopping__ask_price__core_phrase__how_much',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['shopping__ask_price__core_phrase__how_much'],
        aiRole: null,
      },
      {
        id: 'shopping__ask_price__lesson__step_3',
        lessonId: 'shopping__ask_price__lesson',
        orderIndex: 3,
        type: 'pattern',
        prompt: 'Ask the price: How much is ___?',
        instruction: '値段を聞く言い方：How much is ___?',
        hint: 'this / that など。',
        exampleAnswer: 'How much is that?',
        expectedAnswer: 'How much is [item]?',
        basePhraseId: null,
        patternSlotName: 'item',
        patternSlotOptions: [
          { value: 'this', label: 'これ' },
          { value: 'that', label: 'あれ' },
        ],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'shopping__ask_price__lesson__step_4',
        lessonId: 'shopping__ask_price__lesson',
        orderIndex: 4,
        type: 'guided',
        prompt: 'You are the customer. Ask the clerk the price of an item.',
        instruction: 'お客さんです。店員に値段を聞いてください。',
        hint: 'How much is this? でOK。',
        exampleAnswer: 'How much is this?',
        expectedAnswer: 'How much is this?',
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['shopping__ask_price__core_phrase__how_much'],
        aiRole: 'clerk',
      },
      {
        id: 'shopping__ask_price__lesson__step_5',
        lessonId: 'shopping__ask_price__lesson',
        orderIndex: 5,
        type: 'free_conversation',
        prompt: 'You are shopping. Ask about one or two items and respond to the price.',
        instruction: '買い物中です。1〜2品の値段を聞き、答えに反応しましょう。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: 'clerk',
      },
    ],
    phraseIds: [
      'shopping__ask_price__core_phrase__how_much',
      'shopping__ask_price__scene_expression__dollars',
    ],
    isReviewLesson: false,
    isActive: true,
  },
  {
    id: 'restaurant__order_food__lesson',
    sceneId: 'restaurant',
    microSituationId: 'restaurant__order_food',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    title: '注文する',
    description: '料理や飲み物を注文する',
    goal: '注文ができる',
    difficulty: 2,
    estimatedMinutes: 5,
    stepTypes: ['listen', 'repeat', 'pattern', 'guided', 'free_conversation'],
    steps: [
      {
        id: 'restaurant__order_food__lesson__step_1',
        lessonId: 'restaurant__order_food__lesson',
        orderIndex: 1,
        type: 'listen',
        prompt: 'Listen to the order phrase.',
        instruction: '注文のフレーズを聞いてください。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: 'restaurant__order_food__core_phrase__id_like',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'restaurant__order_food__lesson__step_2',
        lessonId: 'restaurant__order_food__lesson',
        orderIndex: 2,
        type: 'repeat',
        prompt: "Say: I'd like the salad, please.",
        instruction: '言ってみましょう。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: "I'd like the salad, please.",
        basePhraseId: 'restaurant__order_food__core_phrase__id_like',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['restaurant__order_food__core_phrase__id_like'],
        aiRole: null,
      },
      {
        id: 'restaurant__order_food__lesson__step_3',
        lessonId: 'restaurant__order_food__lesson',
        orderIndex: 3,
        type: 'pattern',
        prompt: "Order something: I'd like ___, please.",
        instruction: '注文の言い方：I\'d like ___, please.',
        hint: 'the soup / a coffee など。',
        exampleAnswer: "I'd like the soup, please.",
        expectedAnswer: "I'd like [item], please.",
        basePhraseId: 'restaurant__order_food__pattern__id_like',
        patternSlotName: 'item',
        patternSlotOptions: [
          { value: 'the soup', label: 'スープ' },
          { value: 'a coffee', label: 'コーヒー' },
          { value: 'the pasta', label: 'パスタ' },
        ],
        reviewSourcePhraseIds: ['restaurant__order_food__pattern__id_like'],
        aiRole: null,
      },
      {
        id: 'restaurant__order_food__lesson__step_4',
        lessonId: 'restaurant__order_food__lesson',
        orderIndex: 4,
        type: 'guided',
        prompt: "The waiter says: What would you like? Order one dish or drink.",
        instruction: 'ウェイターが「ご注文は？」と言いました。一品か飲み物を注文してください。',
        hint: null,
        exampleAnswer: "I'd like the salad, please.",
        expectedAnswer: "I'd like [item], please.",
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['restaurant__order_food__core_phrase__id_like'],
        aiRole: 'waiter',
      },
      {
        id: 'restaurant__order_food__lesson__step_5',
        lessonId: 'restaurant__order_food__lesson',
        orderIndex: 5,
        type: 'free_conversation',
        prompt: 'Order your meal at the restaurant. Keep it to this scene.',
        instruction: 'レストランで食事を注文しましょう。この場面のまま短く。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: 'waiter',
      },
    ],
    phraseIds: [
      'restaurant__order_food__core_phrase__id_like',
      'restaurant__order_food__pattern__id_like',
    ],
    isReviewLesson: false,
    isActive: true,
  },
  {
    id: 'meet_friend__greeting__lesson',
    sceneId: 'meet_friend',
    microSituationId: 'meet_friend__greeting',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    title: '友達に挨拶する',
    description: '友達と会ったときの挨拶',
    goal: '友達に挨拶できる',
    difficulty: 2,
    estimatedMinutes: 4,
    stepTypes: ['listen', 'repeat', 'pattern', 'guided', 'free_conversation'],
    steps: [
      {
        id: 'meet_friend__greeting__lesson__step_1',
        lessonId: 'meet_friend__greeting__lesson',
        orderIndex: 1,
        type: 'listen',
        prompt: 'Listen to the greeting.',
        instruction: '挨拶を聞いてください。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: 'meet_friend__greeting__core_phrase__hey',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'meet_friend__greeting__lesson__step_2',
        lessonId: 'meet_friend__greeting__lesson',
        orderIndex: 2,
        type: 'repeat',
        prompt: "Say: Hey! Good to see you.",
        instruction: '言ってみましょう。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: 'Hey! Good to see you.',
        basePhraseId: 'meet_friend__greeting__core_phrase__hey',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['meet_friend__greeting__core_phrase__hey'],
        aiRole: null,
      },
      {
        id: 'meet_friend__greeting__lesson__step_3',
        lessonId: 'meet_friend__greeting__lesson',
        orderIndex: 3,
        type: 'pattern',
        prompt: 'Say you are happy to see someone: Good to see you. / Nice to see you.',
        instruction: '会えて嬉しいと言いましょう。',
        hint: null,
        exampleAnswer: 'Nice to see you.',
        expectedAnswer: null,
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'meet_friend__greeting__lesson__step_4',
        lessonId: 'meet_friend__greeting__lesson',
        orderIndex: 4,
        type: 'guided',
        prompt: 'Your friend says: Hey! Good to see you. Respond naturally.',
        instruction: '友達が「やあ、会えて嬉しい」と言いました。自然に返しましょう。',
        hint: 'Same here! が使えます。',
        exampleAnswer: 'Same here!',
        expectedAnswer: 'Same here!',
        basePhraseId: 'meet_friend__greeting__guided_answer__same_here',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['meet_friend__greeting__guided_answer__same_here'],
        aiRole: 'friend',
      },
      {
        id: 'meet_friend__greeting__lesson__step_5',
        lessonId: 'meet_friend__greeting__lesson',
        orderIndex: 5,
        type: 'free_conversation',
        prompt: 'Greet a friend and have a very short casual exchange.',
        instruction: '友達に挨拶して、短いカジュアルなやりとりをしましょう。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: 'friend',
      },
    ],
    phraseIds: [
      'meet_friend__greeting__core_phrase__hey',
      'meet_friend__greeting__guided_answer__same_here',
    ],
    isReviewLesson: false,
    isActive: true,
  },
  {
    id: 'office_greeting__greet_coworkers__lesson',
    sceneId: 'office_greeting',
    microSituationId: 'office_greeting__greet_coworkers',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    title: '同僚に挨拶する',
    description: '出社して同僚に挨拶する',
    goal: '同僚に挨拶できる',
    difficulty: 2,
    estimatedMinutes: 4,
    stepTypes: ['listen', 'repeat', 'pattern', 'guided', 'free_conversation'],
    steps: [
      {
        id: 'office_greeting__greet_coworkers__lesson__step_1',
        lessonId: 'office_greeting__greet_coworkers__lesson',
        orderIndex: 1,
        type: 'listen',
        prompt: 'Listen to the workplace greeting.',
        instruction: '職場の挨拶を聞いてください。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: 'office_greeting__greet_coworkers__core_phrase__good_morning',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'office_greeting__greet_coworkers__lesson__step_2',
        lessonId: 'office_greeting__greet_coworkers__lesson',
        orderIndex: 2,
        type: 'repeat',
        prompt: 'Say: Good morning. How are you?',
        instruction: '言ってみましょう。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: 'Good morning. How are you?',
        basePhraseId: 'office_greeting__greet_coworkers__core_phrase__good_morning',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['office_greeting__greet_coworkers__core_phrase__good_morning'],
        aiRole: null,
      },
      {
        id: 'office_greeting__greet_coworkers__lesson__step_3',
        lessonId: 'office_greeting__greet_coworkers__lesson',
        orderIndex: 3,
        type: 'pattern',
        prompt: 'Greet and ask: Good morning. / Good afternoon. How are you?',
        instruction: '挨拶と一声：Good morning. How are you?',
        hint: null,
        exampleAnswer: 'Good afternoon. How are you?',
        expectedAnswer: null,
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'office_greeting__greet_coworkers__lesson__step_4',
        lessonId: 'office_greeting__greet_coworkers__lesson',
        orderIndex: 4,
        type: 'guided',
        prompt: 'A coworker says: Good morning. How are you? Respond.',
        instruction: '同僚が「おはよう、元気？」と言いました。返答してください。',
        hint: null,
        exampleAnswer: "I'm doing well, thanks.",
        expectedAnswer: "I'm doing well, thanks.",
        basePhraseId: 'office_greeting__greet_coworkers__guided_answer__doing_well',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['office_greeting__greet_coworkers__guided_answer__doing_well'],
        aiRole: 'coworker',
      },
      {
        id: 'office_greeting__greet_coworkers__lesson__step_5',
        lessonId: 'office_greeting__greet_coworkers__lesson',
        orderIndex: 5,
        type: 'free_conversation',
        prompt: 'Greet a coworker at the office and exchange one or two lines.',
        instruction: 'オフィスで同僚に挨拶し、一言二言やりとりしましょう。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: 'coworker',
      },
    ],
    phraseIds: [
      'office_greeting__greet_coworkers__core_phrase__good_morning',
      'office_greeting__greet_coworkers__guided_answer__doing_well',
    ],
    isReviewLesson: false,
    isActive: true,
  },
  {
    id: 'first_date__greeting__lesson',
    sceneId: 'first_date',
    microSituationId: 'first_date__greeting',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    title: '挨拶',
    description: '初デートの挨拶',
    goal: 'デートの挨拶ができる',
    difficulty: 3,
    estimatedMinutes: 5,
    stepTypes: ['listen', 'repeat', 'pattern', 'guided', 'free_conversation'],
    steps: [
      {
        id: 'first_date__greeting__lesson__step_1',
        lessonId: 'first_date__greeting__lesson',
        orderIndex: 1,
        type: 'listen',
        prompt: 'Listen to the greeting.',
        instruction: '挨拶を聞いてください。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: 'first_date__greeting__core_phrase__nice_to_meet',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'first_date__greeting__lesson__step_2',
        lessonId: 'first_date__greeting__lesson',
        orderIndex: 2,
        type: 'repeat',
        prompt: "Say: It's nice to meet you.",
        instruction: '言ってみましょう。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: "It's nice to meet you.",
        basePhraseId: 'first_date__greeting__core_phrase__nice_to_meet',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['first_date__greeting__core_phrase__nice_to_meet'],
        aiRole: null,
      },
      {
        id: 'first_date__greeting__lesson__step_3',
        lessonId: 'first_date__greeting__lesson',
        orderIndex: 3,
        type: 'pattern',
        prompt: "Say you are glad to meet: It's nice to meet you. / Good to meet you.",
        instruction: '会えて嬉しいと言いましょう。',
        hint: null,
        exampleAnswer: "Good to meet you.",
        expectedAnswer: null,
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'first_date__greeting__lesson__step_4',
        lessonId: 'first_date__greeting__lesson',
        orderIndex: 4,
        type: 'guided',
        prompt: "Your date says: It's nice to meet you. Respond warmly.",
        instruction: 'デート相手が「お会いできて嬉しいです」と言いました。温かく返しましょう。',
        hint: "You too! や I've been looking forward to this. が使えます。",
        exampleAnswer: "You too! I've been looking forward to this.",
        expectedAnswer: "You too!",
        basePhraseId: 'first_date__greeting__free_conversation_seed__you_too',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['first_date__greeting__free_conversation_seed__you_too'],
        aiRole: 'date',
      },
      {
        id: 'first_date__greeting__lesson__step_5',
        lessonId: 'first_date__greeting__lesson',
        orderIndex: 5,
        type: 'free_conversation',
        prompt: 'Greet your date and have a short, warm exchange. Stay in this scene.',
        instruction: 'デートの挨拶をして、短く温かいやりとりをしましょう。この場面のまま。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: 'date',
      },
    ],
    phraseIds: [
      'first_date__greeting__core_phrase__nice_to_meet',
      'first_date__greeting__free_conversation_seed__you_too',
    ],
    isReviewLesson: false,
    isActive: true,
  },
  {
    id: 'describe_symptom__what_hurts__lesson',
    sceneId: 'describe_symptom',
    microSituationId: 'describe_symptom__what_hurts',
    targetLanguageCode: 'en',
    regionVariant: 'default',
    title: 'どこが痛いか言う',
    description: '痛みの場所や程度を伝える',
    goal: '症状を伝えられる',
    difficulty: 2,
    estimatedMinutes: 5,
    stepTypes: ['listen', 'repeat', 'pattern', 'guided', 'free_conversation'],
    steps: [
      {
        id: 'describe_symptom__what_hurts__lesson__step_1',
        lessonId: 'describe_symptom__what_hurts__lesson',
        orderIndex: 1,
        type: 'listen',
        prompt: 'Listen to the symptom phrase.',
        instruction: '症状の言い方を聞いてください。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: 'describe_symptom__what_hurts__core_phrase__headache',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: null,
      },
      {
        id: 'describe_symptom__what_hurts__lesson__step_2',
        lessonId: 'describe_symptom__what_hurts__lesson',
        orderIndex: 2,
        type: 'repeat',
        prompt: "Say: I have a headache.",
        instruction: '言ってみましょう。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: "I have a headache.",
        basePhraseId: 'describe_symptom__what_hurts__core_phrase__headache',
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['describe_symptom__what_hurts__core_phrase__headache'],
        aiRole: null,
      },
      {
        id: 'describe_symptom__what_hurts__lesson__step_3',
        lessonId: 'describe_symptom__what_hurts__lesson',
        orderIndex: 3,
        type: 'pattern',
        prompt: "Describe a symptom: I have a ___.",
        instruction: '症状を言う：I have a ___.',
        hint: 'headache / stomachache / sore throat',
        exampleAnswer: "I have a stomachache.",
        expectedAnswer: "I have a [symptom].",
        basePhraseId: 'describe_symptom__what_hurts__pattern__i_have_a',
        patternSlotName: 'symptom',
        patternSlotOptions: [
          { value: 'headache', label: '頭痛' },
          { value: 'stomachache', label: '腹痛' },
          { value: 'sore throat', label: '喉の痛み' },
        ],
        reviewSourcePhraseIds: ['describe_symptom__what_hurts__pattern__i_have_a'],
        aiRole: null,
      },
      {
        id: 'describe_symptom__what_hurts__lesson__step_4',
        lessonId: 'describe_symptom__what_hurts__lesson',
        orderIndex: 4,
        type: 'guided',
        prompt: "The doctor or nurse asks: What's wrong? Describe one simple symptom.",
        instruction: '医師や看護師が「どうしましたか」と聞きました。一つ症状を伝えてください。',
        hint: null,
        exampleAnswer: "I have a headache.",
        expectedAnswer: "I have a [symptom].",
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: ['describe_symptom__what_hurts__core_phrase__headache'],
        aiRole: 'nurse',
      },
      {
        id: 'describe_symptom__what_hurts__lesson__step_5',
        lessonId: 'describe_symptom__what_hurts__lesson',
        orderIndex: 5,
        type: 'free_conversation',
        prompt: 'Tell the nurse or doctor what hurts. Keep it simple and scene-bound.',
        instruction: '看護師や医師にどこが痛いか伝えましょう。簡単に、この場面のまま。',
        hint: null,
        exampleAnswer: null,
        expectedAnswer: null,
        basePhraseId: null,
        patternSlotName: null,
        patternSlotOptions: [],
        reviewSourcePhraseIds: [],
        aiRole: 'nurse',
      },
    ],
    phraseIds: [
      'describe_symptom__what_hurts__core_phrase__headache',
      'describe_symptom__what_hurts__pattern__i_have_a',
    ],
    isReviewLesson: false,
    isActive: true,
  },
]

export const MVP_REVIEW_SOURCE_LINKS: ReviewSourceLink[] = [
  {
    phraseId: 'wake_up__morning_greeting__core_phrase__good_morning',
    lessonId: 'wake_up__morning_greeting__lesson',
    sceneId: 'wake_up',
    microSituationId: 'wake_up__morning_greeting',
    sourceStepType: 'repeat',
    sourceTurnGoal: '朝の挨拶を言う',
  },
  {
    phraseId: 'wake_up__morning_greeting__scene_expression__slept_well',
    lessonId: 'wake_up__morning_greeting__lesson',
    sceneId: 'wake_up',
    microSituationId: 'wake_up__morning_greeting',
    sourceStepType: 'guided',
    sourceTurnGoal: 'よく眠れたと答える',
  },
  {
    phraseId: 'breakfast__say_what_you_ate__core_phrase__had_eggs',
    lessonId: 'breakfast__say_what_you_ate__lesson',
    sceneId: 'breakfast',
    microSituationId: 'breakfast__say_what_you_ate',
    sourceStepType: 'repeat',
    sourceTurnGoal: '食べた内容を言う',
  },
  {
    phraseId: 'breakfast__say_what_you_ate__pattern__i_had',
    lessonId: 'breakfast__say_what_you_ate__lesson',
    sceneId: 'breakfast',
    microSituationId: 'breakfast__say_what_you_ate',
    sourceStepType: 'pattern',
    sourceTurnGoal: 'I had ___. で言う',
  },
  {
    phraseId: 'shopping__ask_price__core_phrase__how_much',
    lessonId: 'shopping__ask_price__lesson',
    sceneId: 'shopping',
    microSituationId: 'shopping__ask_price',
    sourceStepType: 'repeat',
    sourceTurnGoal: '値段を聞く',
  },
  {
    phraseId: 'shopping__ask_price__scene_expression__dollars',
    lessonId: 'shopping__ask_price__lesson',
    sceneId: 'shopping',
    microSituationId: 'shopping__ask_price',
    sourceStepType: 'guided',
    sourceTurnGoal: '値段を答える',
  },
  {
    phraseId: 'restaurant__order_food__core_phrase__id_like',
    lessonId: 'restaurant__order_food__lesson',
    sceneId: 'restaurant',
    microSituationId: 'restaurant__order_food',
    sourceStepType: 'repeat',
    sourceTurnGoal: '注文のフレーズを言う',
  },
  {
    phraseId: 'restaurant__order_food__pattern__id_like',
    lessonId: 'restaurant__order_food__lesson',
    sceneId: 'restaurant',
    microSituationId: 'restaurant__order_food',
    sourceStepType: 'pattern',
    sourceTurnGoal: 'I\'d like ___, please. で注文',
  },
  {
    phraseId: 'meet_friend__greeting__core_phrase__hey',
    lessonId: 'meet_friend__greeting__lesson',
    sceneId: 'meet_friend',
    microSituationId: 'meet_friend__greeting',
    sourceStepType: 'repeat',
    sourceTurnGoal: '友達に挨拶する',
  },
  {
    phraseId: 'meet_friend__greeting__guided_answer__same_here',
    lessonId: 'meet_friend__greeting__lesson',
    sceneId: 'meet_friend',
    microSituationId: 'meet_friend__greeting',
    sourceStepType: 'guided',
    sourceTurnGoal: 'Same here! で返す',
  },
  {
    phraseId: 'office_greeting__greet_coworkers__core_phrase__good_morning',
    lessonId: 'office_greeting__greet_coworkers__lesson',
    sceneId: 'office_greeting',
    microSituationId: 'office_greeting__greet_coworkers',
    sourceStepType: 'repeat',
    sourceTurnGoal: '同僚に挨拶する',
  },
  {
    phraseId: 'office_greeting__greet_coworkers__guided_answer__doing_well',
    lessonId: 'office_greeting__greet_coworkers__lesson',
    sceneId: 'office_greeting',
    microSituationId: 'office_greeting__greet_coworkers',
    sourceStepType: 'guided',
    sourceTurnGoal: '元気だと答える',
  },
  {
    phraseId: 'first_date__greeting__core_phrase__nice_to_meet',
    lessonId: 'first_date__greeting__lesson',
    sceneId: 'first_date',
    microSituationId: 'first_date__greeting',
    sourceStepType: 'repeat',
    sourceTurnGoal: 'お会いできて嬉しいと言う',
  },
  {
    phraseId: 'first_date__greeting__free_conversation_seed__you_too',
    lessonId: 'first_date__greeting__lesson',
    sceneId: 'first_date',
    microSituationId: 'first_date__greeting',
    sourceStepType: 'guided',
    sourceTurnGoal: '温かく返す',
  },
  {
    phraseId: 'describe_symptom__what_hurts__core_phrase__headache',
    lessonId: 'describe_symptom__what_hurts__lesson',
    sceneId: 'describe_symptom',
    microSituationId: 'describe_symptom__what_hurts',
    sourceStepType: 'repeat',
    sourceTurnGoal: '頭が痛いと伝える',
  },
  {
    phraseId: 'describe_symptom__what_hurts__pattern__i_have_a',
    lessonId: 'describe_symptom__what_hurts__lesson',
    sceneId: 'describe_symptom',
    microSituationId: 'describe_symptom__what_hurts',
    sourceStepType: 'pattern',
    sourceTurnGoal: 'I have a ___. で症状を言う',
  },
]

export const MVP_LESSON_IDS: string[] = [
  'wake_up__morning_greeting__lesson',
  'breakfast__say_what_you_ate__lesson',
  'shopping__ask_price__lesson',
  'restaurant__order_food__lesson',
  'meet_friend__greeting__lesson',
  'office_greeting__greet_coworkers__lesson',
  'first_date__greeting__lesson',
  'describe_symptom__what_hurts__lesson',
]