import type {
  SceneDefinition,
  MicroSituationDefinition,
  SceneTaxonomyNode,
} from './lesson-domain-types'

/**
 * World setting: real-world only.
 * Scene and story generation assume realistic locations and daily-life contexts:
 * cafe, office, airport, shopping, restaurant, travel, hotel, dating, etc.
 * No fantasy or fictional worlds; keep settings grounded in the real world.
 */
export const MVP_SCENES: SceneDefinition[] = [
  {
    id: 'wake_up',
    slug: 'wake_up',
    lifeCategory: 'daily_life',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: '朝の起床',
    description: '朝起きて一日を始める場面',
    roleUser: '学習者（自分）',
    roleAI: '家族・ルームメイト',
    difficulty: 1,
    isActive: true,
  },
  {
    id: 'breakfast',
    slug: 'breakfast',
    lifeCategory: 'daily_life',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: '朝食',
    description: '朝食を取る場面',
    roleUser: '学習者（自分）',
    roleAI: '家族・店員',
    difficulty: 1,
    isActive: true,
  },
  {
    id: 'commute',
    slug: 'commute',
    lifeCategory: 'daily_life',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: '通勤・通学',
    description: '電車やバスでの移動中の会話',
    roleUser: '学習者（自分）',
    roleAI: '同乗者・駅員',
    difficulty: 2,
    isActive: true,
  },
  {
    id: 'shopping',
    slug: 'shopping',
    lifeCategory: 'daily_life',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: '買い物',
    description: '店で商品を選んだり聞いたりする場面',
    roleUser: 'お客さん',
    roleAI: '店員',
    difficulty: 2,
    isActive: true,
  },
  {
    id: 'restaurant',
    slug: 'restaurant',
    lifeCategory: 'daily_life',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: 'レストラン',
    description: '注文や会計など食事の場面',
    roleUser: 'お客さん',
    roleAI: 'ウェイター・店員',
    difficulty: 2,
    isActive: true,
  },
  {
    id: 'sleep',
    slug: 'sleep',
    lifeCategory: 'daily_life',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: '就寝前',
    description: '寝る前の短い会話',
    roleUser: '学習者（自分）',
    roleAI: '家族・ルームメイト',
    difficulty: 1,
    isActive: true,
  },
  {
    id: 'meet_friend',
    slug: 'meet_friend',
    lifeCategory: 'social_life',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: '友達に会う',
    description: '友達と待ち合わせて会う場面',
    roleUser: '学習者（自分）',
    roleAI: '友達',
    difficulty: 2,
    isActive: true,
  },
  {
    id: 'small_talk',
    slug: 'small_talk',
    lifeCategory: 'social_life',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: '雑談',
    description: '週末や趣味などの軽い会話',
    roleUser: '学習者（自分）',
    roleAI: '知り合い・同僚',
    difficulty: 2,
    isActive: true,
  },
  {
    id: 'office_greeting',
    slug: 'office_greeting',
    lifeCategory: 'work_life',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: 'オフィスでの挨拶',
    description: '出社時や同僚との挨拶',
    roleUser: '社員',
    roleAI: '同僚',
    difficulty: 2,
    isActive: true,
  },
  {
    id: 'ask_for_help',
    slug: 'ask_for_help',
    lifeCategory: 'work_life',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: '助けを求める',
    description: '仕事で手伝いを頼んだり確認したりする場面',
    roleUser: '社員',
    roleAI: '同僚・上司',
    difficulty: 3,
    isActive: true,
  },
  {
    id: 'airport_checkin',
    slug: 'airport_checkin',
    lifeCategory: 'travel',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: '空港チェックイン',
    description: '搭乗手続きや荷物の確認',
    roleUser: '乗客',
    roleAI: 'スタッフ',
    difficulty: 3,
    isActive: true,
  },
  {
    id: 'hotel_checkin',
    slug: 'hotel_checkin',
    lifeCategory: 'travel',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: 'ホテルチェックイン',
    description: '宿泊手続きや朝食などの確認',
    roleUser: '宿泊客',
    roleAI: 'フロント',
    difficulty: 3,
    isActive: true,
  },
  {
    id: 'first_date',
    slug: 'first_date',
    lifeCategory: 'relationships',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: '初デート',
    description: '初デートでの挨拶や食事の提案',
    roleUser: '自分',
    roleAI: 'デート相手',
    difficulty: 3,
    isActive: true,
  },
  {
    id: 'text_after_date',
    slug: 'text_after_date',
    lifeCategory: 'relationships',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: 'デート後のメッセージ',
    description: 'お礼や次回の提案を伝える',
    roleUser: '自分',
    roleAI: '相手（メッセージの相手）',
    difficulty: 3,
    isActive: true,
  },
  {
    id: 'express_feelings',
    slug: 'express_feelings',
    lifeCategory: 'relationships',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: '気持ちを伝える',
    description: '褒めたり気持ちを言葉にする場面',
    roleUser: '自分',
    roleAI: '相手',
    difficulty: 4,
    isActive: true,
  },
  {
    id: 'describe_symptom',
    slug: 'describe_symptom',
    lifeCategory: 'health',
    targetLanguageCode: 'en',
    targetCountryCode: null,
    regionVariant: 'default',
    title: '症状を伝える',
    description: '痛みや症状を説明し、簡単な質問に答える',
    roleUser: '患者',
    roleAI: '医師・看護師',
    difficulty: 4,
    isActive: true,
  },
]

export const MVP_MICRO_SITUATIONS: MicroSituationDefinition[] = [
  {
    id: 'wake_up__morning_greeting',
    sceneId: 'wake_up',
    slug: 'morning_greeting',
    title: '朝の挨拶',
    description: '朝起きたときの挨拶',
    goal: '朝の挨拶ができる',
    difficulty: 1,
    estimatedMinutes: 3,
    isActive: true,
  },
  {
    id: 'wake_up__talk_about_sleep',
    sceneId: 'wake_up',
    slug: 'talk_about_sleep',
    title: '睡眠について話す',
    description: 'よく眠れたかなど短く話す',
    goal: '睡眠について一言話せる',
    difficulty: 1,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'breakfast__choose_food',
    sceneId: 'breakfast',
    slug: 'choose_food',
    title: '食べるものを選ぶ',
    description: '朝食に何を食べるか言う',
    goal: '朝食の選択が言える',
    difficulty: 1,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'breakfast__say_what_you_ate',
    sceneId: 'breakfast',
    slug: 'say_what_you_ate',
    title: '食べたものを言う',
    description: '何を食べたか伝える',
    goal: '食べた内容を伝えられる',
    difficulty: 1,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'commute__ask_destination',
    sceneId: 'commute',
    slug: 'ask_destination',
    title: '行き先を聞く',
    description: 'どこへ行くか聞いたり答える',
    goal: '行き先のやりとりができる',
    difficulty: 2,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'commute__talk_about_transport',
    sceneId: 'commute',
    slug: 'talk_about_transport',
    title: '交通手段について話す',
    description: '電車やバスについて短く話す',
    goal: '交通手段について話せる',
    difficulty: 2,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'shopping__ask_price',
    sceneId: 'shopping',
    slug: 'ask_price',
    title: '値段を聞く',
    description: '商品の値段を聞く',
    goal: '値段を聞いて答えられる',
    difficulty: 2,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'shopping__ask_size_color',
    sceneId: 'shopping',
    slug: 'ask_size_color',
    title: 'サイズ・色を聞く',
    description: 'サイズや色を聞いたり答える',
    goal: 'サイズ・色のやりとりができる',
    difficulty: 2,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'restaurant__order_food',
    sceneId: 'restaurant',
    slug: 'order_food',
    title: '注文する',
    description: '料理や飲み物を注文する',
    goal: '注文ができる',
    difficulty: 2,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'restaurant__ask_for_bill',
    sceneId: 'restaurant',
    slug: 'ask_for_bill',
    title: '会計を頼む',
    description: 'お会計を頼む',
    goal: '会計を頼める',
    difficulty: 2,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'sleep__talk_about_tired',
    sceneId: 'sleep',
    slug: 'talk_about_tired',
    title: '疲れについて話す',
    description: '疲れたと言う・明日の話をする',
    goal: '疲れや明日の話ができる',
    difficulty: 1,
    estimatedMinutes: 3,
    isActive: true,
  },
  {
    id: 'sleep__talk_about_tomorrow',
    sceneId: 'sleep',
    slug: 'talk_about_tomorrow',
    title: '明日の予定を話す',
    description: '明日何をするか短く話す',
    goal: '明日の予定を伝えられる',
    difficulty: 1,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'meet_friend__greeting',
    sceneId: 'meet_friend',
    slug: 'greeting',
    title: '友達に挨拶する',
    description: '友達と会ったときの挨拶',
    goal: '友達に挨拶できる',
    difficulty: 2,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'meet_friend__make_plan',
    sceneId: 'meet_friend',
    slug: 'make_plan',
    title: '予定を決める',
    description: '次に何をするか決める',
    goal: '簡単な予定が決められる',
    difficulty: 2,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'small_talk__weekend',
    sceneId: 'small_talk',
    slug: 'weekend',
    title: '週末の話',
    description: '週末何をしたか話す',
    goal: '週末の話ができる',
    difficulty: 2,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'small_talk__hobbies',
    sceneId: 'small_talk',
    slug: 'hobbies',
    title: '趣味の話',
    description: '趣味について短く話す',
    goal: '趣味について話せる',
    difficulty: 2,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'office_greeting__greet_coworkers',
    sceneId: 'office_greeting',
    slug: 'greet_coworkers',
    title: '同僚に挨拶する',
    description: '出社して同僚に挨拶する',
    goal: '同僚に挨拶できる',
    difficulty: 2,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'office_greeting__start_day',
    sceneId: 'office_greeting',
    slug: 'start_day',
    title: '一日の始まり',
    description: '今日の予定を短く話す',
    goal: '一日の始まりの会話ができる',
    difficulty: 2,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'ask_for_help__ask_help',
    sceneId: 'ask_for_help',
    slug: 'ask_help',
    title: '手伝いを頼む',
    description: '仕事で手伝いを頼む',
    goal: '手伝いを頼める',
    difficulty: 3,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'ask_for_help__clarify_task',
    sceneId: 'ask_for_help',
    slug: 'clarify_task',
    title: '作業内容を確認する',
    description: 'タスクの内容を確認する',
    goal: '作業内容の確認ができる',
    difficulty: 3,
    estimatedMinutes: 6,
    isActive: true,
  },
  {
    id: 'airport_checkin__check_in',
    sceneId: 'airport_checkin',
    slug: 'check_in',
    title: '搭乗手続き',
    description: 'チェックインで手続きする',
    goal: '搭乗手続きができる',
    difficulty: 3,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'airport_checkin__confirm_baggage',
    sceneId: 'airport_checkin',
    slug: 'confirm_baggage',
    title: '荷物の確認',
    description: '預け荷物について確認する',
    goal: '荷物についてやりとりできる',
    difficulty: 3,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'hotel_checkin__check_in',
    sceneId: 'hotel_checkin',
    slug: 'check_in',
    title: 'チェックイン',
    description: '宿泊の手続きをする',
    goal: 'チェックインができる',
    difficulty: 3,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'hotel_checkin__ask_breakfast',
    sceneId: 'hotel_checkin',
    slug: 'ask_breakfast',
    title: '朝食について聞く',
    description: '朝食の時間や場所を聞く',
    goal: '朝食について聞ける',
    difficulty: 3,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'first_date__greeting',
    sceneId: 'first_date',
    slug: 'greeting',
    title: '挨拶',
    description: '初デートの挨拶',
    goal: 'デートの挨拶ができる',
    difficulty: 3,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'first_date__suggest_food_drink',
    sceneId: 'first_date',
    slug: 'suggest_food_drink',
    title: '食事・飲み物を提案する',
    description: '何を食べるか・飲むか提案する',
    goal: '食事や飲み物の提案ができる',
    difficulty: 3,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'text_after_date__say_thanks',
    sceneId: 'text_after_date',
    slug: 'say_thanks',
    title: 'お礼を伝える',
    description: 'デートのお礼をメッセージで伝える',
    goal: 'お礼のメッセージが書ける',
    difficulty: 3,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'text_after_date__suggest_next',
    sceneId: 'text_after_date',
    slug: 'suggest_next',
    title: '次回を提案する',
    description: 'また会おうと提案する',
    goal: '次回の提案ができる',
    difficulty: 3,
    estimatedMinutes: 4,
    isActive: true,
  },
  {
    id: 'express_feelings__compliment',
    sceneId: 'express_feelings',
    slug: 'compliment',
    title: '褒める',
    description: '相手を褒める',
    goal: '自然に褒められる',
    difficulty: 4,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'express_feelings__say_how_you_feel',
    sceneId: 'express_feelings',
    slug: 'say_how_you_feel',
    title: '気持ちを言う',
    description: '自分の気持ちを言葉にする',
    goal: '気持ちを伝えられる',
    difficulty: 4,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'describe_symptom__what_hurts',
    sceneId: 'describe_symptom',
    slug: 'what_hurts',
    title: 'どこが痛いか言う',
    description: '痛みの場所や程度を伝える',
    goal: '症状を伝えられる',
    difficulty: 4,
    estimatedMinutes: 5,
    isActive: true,
  },
  {
    id: 'describe_symptom__answer_doctor',
    sceneId: 'describe_symptom',
    slug: 'answer_doctor',
    title: '医師の質問に答える',
    description: '簡単な問診に答える',
    goal: '医師の質問に答えられる',
    difficulty: 4,
    estimatedMinutes: 6,
    isActive: true,
  },
]

export const MVP_SCENE_TAXONOMY: SceneTaxonomyNode[] = [
  {
    lifeCategory: 'daily_life',
    scenes: [
      {
        id: 'wake_up',
        slug: 'wake_up',
        lifeCategory: 'daily_life',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: '朝の起床',
        description: '朝起きて一日を始める場面',
        roleUser: '学習者（自分）',
        roleAI: '家族・ルームメイト',
        difficulty: 1,
        isActive: true,
      },
      {
        id: 'breakfast',
        slug: 'breakfast',
        lifeCategory: 'daily_life',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: '朝食',
        description: '朝食を取る場面',
        roleUser: '学習者（自分）',
        roleAI: '家族・店員',
        difficulty: 1,
        isActive: true,
      },
      {
        id: 'commute',
        slug: 'commute',
        lifeCategory: 'daily_life',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: '通勤・通学',
        description: '電車やバスでの移動中の会話',
        roleUser: '学習者（自分）',
        roleAI: '同乗者・駅員',
        difficulty: 2,
        isActive: true,
      },
      {
        id: 'shopping',
        slug: 'shopping',
        lifeCategory: 'daily_life',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: '買い物',
        description: '店で商品を選んだり聞いたりする場面',
        roleUser: 'お客さん',
        roleAI: '店員',
        difficulty: 2,
        isActive: true,
      },
      {
        id: 'restaurant',
        slug: 'restaurant',
        lifeCategory: 'daily_life',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: 'レストラン',
        description: '注文や会計など食事の場面',
        roleUser: 'お客さん',
        roleAI: 'ウェイター・店員',
        difficulty: 2,
        isActive: true,
      },
      {
        id: 'sleep',
        slug: 'sleep',
        lifeCategory: 'daily_life',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: '就寝前',
        description: '寝る前の短い会話',
        roleUser: '学習者（自分）',
        roleAI: '家族・ルームメイト',
        difficulty: 1,
        isActive: true,
      },
    ],
    microSituations: [
      {
        id: 'wake_up__morning_greeting',
        sceneId: 'wake_up',
        slug: 'morning_greeting',
        title: '朝の挨拶',
        description: '朝起きたときの挨拶',
        goal: '朝の挨拶ができる',
        difficulty: 1,
        estimatedMinutes: 3,
        isActive: true,
      },
      {
        id: 'wake_up__talk_about_sleep',
        sceneId: 'wake_up',
        slug: 'talk_about_sleep',
        title: '睡眠について話す',
        description: 'よく眠れたかなど短く話す',
        goal: '睡眠について一言話せる',
        difficulty: 1,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'breakfast__choose_food',
        sceneId: 'breakfast',
        slug: 'choose_food',
        title: '食べるものを選ぶ',
        description: '朝食に何を食べるか言う',
        goal: '朝食の選択が言える',
        difficulty: 1,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'breakfast__say_what_you_ate',
        sceneId: 'breakfast',
        slug: 'say_what_you_ate',
        title: '食べたものを言う',
        description: '何を食べたか伝える',
        goal: '食べた内容を伝えられる',
        difficulty: 1,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'commute__ask_destination',
        sceneId: 'commute',
        slug: 'ask_destination',
        title: '行き先を聞く',
        description: 'どこへ行くか聞いたり答える',
        goal: '行き先のやりとりができる',
        difficulty: 2,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'commute__talk_about_transport',
        sceneId: 'commute',
        slug: 'talk_about_transport',
        title: '交通手段について話す',
        description: '電車やバスについて短く話す',
        goal: '交通手段について話せる',
        difficulty: 2,
        estimatedMinutes: 5,
        isActive: true,
      },
      {
        id: 'shopping__ask_price',
        sceneId: 'shopping',
        slug: 'ask_price',
        title: '値段を聞く',
        description: '商品の値段を聞く',
        goal: '値段を聞いて答えられる',
        difficulty: 2,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'shopping__ask_size_color',
        sceneId: 'shopping',
        slug: 'ask_size_color',
        title: 'サイズ・色を聞く',
        description: 'サイズや色を聞いたり答える',
        goal: 'サイズ・色のやりとりができる',
        difficulty: 2,
        estimatedMinutes: 5,
        isActive: true,
      },
      {
        id: 'restaurant__order_food',
        sceneId: 'restaurant',
        slug: 'order_food',
        title: '注文する',
        description: '料理や飲み物を注文する',
        goal: '注文ができる',
        difficulty: 2,
        estimatedMinutes: 5,
        isActive: true,
      },
      {
        id: 'restaurant__ask_for_bill',
        sceneId: 'restaurant',
        slug: 'ask_for_bill',
        title: '会計を頼む',
        description: 'お会計を頼む',
        goal: '会計を頼める',
        difficulty: 2,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'sleep__talk_about_tired',
        sceneId: 'sleep',
        slug: 'talk_about_tired',
        title: '疲れについて話す',
        description: '疲れたと言う・明日の話をする',
        goal: '疲れや明日の話ができる',
        difficulty: 1,
        estimatedMinutes: 3,
        isActive: true,
      },
      {
        id: 'sleep__talk_about_tomorrow',
        sceneId: 'sleep',
        slug: 'talk_about_tomorrow',
        title: '明日の予定を話す',
        description: '明日何をするか短く話す',
        goal: '明日の予定を伝えられる',
        difficulty: 1,
        estimatedMinutes: 4,
        isActive: true,
      },
    ],
  },
  {
    lifeCategory: 'social_life',
    scenes: [
      {
        id: 'meet_friend',
        slug: 'meet_friend',
        lifeCategory: 'social_life',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: '友達に会う',
        description: '友達と待ち合わせて会う場面',
        roleUser: '学習者（自分）',
        roleAI: '友達',
        difficulty: 2,
        isActive: true,
      },
      {
        id: 'small_talk',
        slug: 'small_talk',
        lifeCategory: 'social_life',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: '雑談',
        description: '週末や趣味などの軽い会話',
        roleUser: '学習者（自分）',
        roleAI: '知り合い・同僚',
        difficulty: 2,
        isActive: true,
      },
    ],
    microSituations: [
      {
        id: 'meet_friend__greeting',
        sceneId: 'meet_friend',
        slug: 'greeting',
        title: '友達に挨拶する',
        description: '友達と会ったときの挨拶',
        goal: '友達に挨拶できる',
        difficulty: 2,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'meet_friend__make_plan',
        sceneId: 'meet_friend',
        slug: 'make_plan',
        title: '予定を決める',
        description: '次に何をするか決める',
        goal: '簡単な予定が決められる',
        difficulty: 2,
        estimatedMinutes: 5,
        isActive: true,
      },
      {
        id: 'small_talk__weekend',
        sceneId: 'small_talk',
        slug: 'weekend',
        title: '週末の話',
        description: '週末何をしたか話す',
        goal: '週末の話ができる',
        difficulty: 2,
        estimatedMinutes: 5,
        isActive: true,
      },
      {
        id: 'small_talk__hobbies',
        sceneId: 'small_talk',
        slug: 'hobbies',
        title: '趣味の話',
        description: '趣味について短く話す',
        goal: '趣味について話せる',
        difficulty: 2,
        estimatedMinutes: 5,
        isActive: true,
      },
    ],
  },
  {
    lifeCategory: 'work_life',
    scenes: [
      {
        id: 'office_greeting',
        slug: 'office_greeting',
        lifeCategory: 'work_life',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: 'オフィスでの挨拶',
        description: '出社時や同僚との挨拶',
        roleUser: '社員',
        roleAI: '同僚',
        difficulty: 2,
        isActive: true,
      },
      {
        id: 'ask_for_help',
        slug: 'ask_for_help',
        lifeCategory: 'work_life',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: '助けを求める',
        description: '仕事で手伝いを頼んだり確認したりする場面',
        roleUser: '社員',
        roleAI: '同僚・上司',
        difficulty: 3,
        isActive: true,
      },
    ],
    microSituations: [
      {
        id: 'office_greeting__greet_coworkers',
        sceneId: 'office_greeting',
        slug: 'greet_coworkers',
        title: '同僚に挨拶する',
        description: '出社して同僚に挨拶する',
        goal: '同僚に挨拶できる',
        difficulty: 2,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'office_greeting__start_day',
        sceneId: 'office_greeting',
        slug: 'start_day',
        title: '一日の始まり',
        description: '今日の予定を短く話す',
        goal: '一日の始まりの会話ができる',
        difficulty: 2,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'ask_for_help__ask_help',
        sceneId: 'ask_for_help',
        slug: 'ask_help',
        title: '手伝いを頼む',
        description: '仕事で手伝いを頼む',
        goal: '手伝いを頼める',
        difficulty: 3,
        estimatedMinutes: 5,
        isActive: true,
      },
      {
        id: 'ask_for_help__clarify_task',
        sceneId: 'ask_for_help',
        slug: 'clarify_task',
        title: '作業内容を確認する',
        description: 'タスクの内容を確認する',
        goal: '作業内容の確認ができる',
        difficulty: 3,
        estimatedMinutes: 6,
        isActive: true,
      },
    ],
  },
  {
    lifeCategory: 'travel',
    scenes: [
      {
        id: 'airport_checkin',
        slug: 'airport_checkin',
        lifeCategory: 'travel',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: '空港チェックイン',
        description: '搭乗手続きや荷物の確認',
        roleUser: '乗客',
        roleAI: 'スタッフ',
        difficulty: 3,
        isActive: true,
      },
      {
        id: 'hotel_checkin',
        slug: 'hotel_checkin',
        lifeCategory: 'travel',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: 'ホテルチェックイン',
        description: '宿泊手続きや朝食などの確認',
        roleUser: '宿泊客',
        roleAI: 'フロント',
        difficulty: 3,
        isActive: true,
      },
    ],
    microSituations: [
      {
        id: 'airport_checkin__check_in',
        sceneId: 'airport_checkin',
        slug: 'check_in',
        title: '搭乗手続き',
        description: 'チェックインで手続きする',
        goal: '搭乗手続きができる',
        difficulty: 3,
        estimatedMinutes: 5,
        isActive: true,
      },
      {
        id: 'airport_checkin__confirm_baggage',
        sceneId: 'airport_checkin',
        slug: 'confirm_baggage',
        title: '荷物の確認',
        description: '預け荷物について確認する',
        goal: '荷物についてやりとりできる',
        difficulty: 3,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'hotel_checkin__check_in',
        sceneId: 'hotel_checkin',
        slug: 'check_in',
        title: 'チェックイン',
        description: '宿泊の手続きをする',
        goal: 'チェックインができる',
        difficulty: 3,
        estimatedMinutes: 5,
        isActive: true,
      },
      {
        id: 'hotel_checkin__ask_breakfast',
        sceneId: 'hotel_checkin',
        slug: 'ask_breakfast',
        title: '朝食について聞く',
        description: '朝食の時間や場所を聞く',
        goal: '朝食について聞ける',
        difficulty: 3,
        estimatedMinutes: 4,
        isActive: true,
      },
    ],
  },
  {
    lifeCategory: 'relationships',
    scenes: [
      {
        id: 'first_date',
        slug: 'first_date',
        lifeCategory: 'relationships',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: '初デート',
        description: '初デートでの挨拶や食事の提案',
        roleUser: '自分',
        roleAI: 'デート相手',
        difficulty: 3,
        isActive: true,
      },
      {
        id: 'text_after_date',
        slug: 'text_after_date',
        lifeCategory: 'relationships',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: 'デート後のメッセージ',
        description: 'お礼や次回の提案を伝える',
        roleUser: '自分',
        roleAI: '相手（メッセージの相手）',
        difficulty: 3,
        isActive: true,
      },
      {
        id: 'express_feelings',
        slug: 'express_feelings',
        lifeCategory: 'relationships',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: '気持ちを伝える',
        description: '褒めたり気持ちを言葉にする場面',
        roleUser: '自分',
        roleAI: '相手',
        difficulty: 4,
        isActive: true,
      },
    ],
    microSituations: [
      {
        id: 'first_date__greeting',
        sceneId: 'first_date',
        slug: 'greeting',
        title: '挨拶',
        description: '初デートの挨拶',
        goal: 'デートの挨拶ができる',
        difficulty: 3,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'first_date__suggest_food_drink',
        sceneId: 'first_date',
        slug: 'suggest_food_drink',
        title: '食事・飲み物を提案する',
        description: '何を食べるか・飲むか提案する',
        goal: '食事や飲み物の提案ができる',
        difficulty: 3,
        estimatedMinutes: 5,
        isActive: true,
      },
      {
        id: 'text_after_date__say_thanks',
        sceneId: 'text_after_date',
        slug: 'say_thanks',
        title: 'お礼を伝える',
        description: 'デートのお礼をメッセージで伝える',
        goal: 'お礼のメッセージが書ける',
        difficulty: 3,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'text_after_date__suggest_next',
        sceneId: 'text_after_date',
        slug: 'suggest_next',
        title: '次回を提案する',
        description: 'また会おうと提案する',
        goal: '次回の提案ができる',
        difficulty: 3,
        estimatedMinutes: 4,
        isActive: true,
      },
      {
        id: 'express_feelings__compliment',
        sceneId: 'express_feelings',
        slug: 'compliment',
        title: '褒める',
        description: '相手を褒める',
        goal: '自然に褒められる',
        difficulty: 4,
        estimatedMinutes: 5,
        isActive: true,
      },
      {
        id: 'express_feelings__say_how_you_feel',
        sceneId: 'express_feelings',
        slug: 'say_how_you_feel',
        title: '気持ちを言う',
        description: '自分の気持ちを言葉にする',
        goal: '気持ちを伝えられる',
        difficulty: 4,
        estimatedMinutes: 5,
        isActive: true,
      },
    ],
  },
  {
    lifeCategory: 'health',
    scenes: [
      {
        id: 'describe_symptom',
        slug: 'describe_symptom',
        lifeCategory: 'health',
        targetLanguageCode: 'en',
        targetCountryCode: null,
        regionVariant: 'default',
        title: '症状を伝える',
        description: '痛みや症状を説明し、簡単な質問に答える',
        roleUser: '患者',
        roleAI: '医師・看護師',
        difficulty: 4,
        isActive: true,
      },
    ],
    microSituations: [
      {
        id: 'describe_symptom__what_hurts',
        sceneId: 'describe_symptom',
        slug: 'what_hurts',
        title: 'どこが痛いか言う',
        description: '痛みの場所や程度を伝える',
        goal: '症状を伝えられる',
        difficulty: 4,
        estimatedMinutes: 5,
        isActive: true,
      },
      {
        id: 'describe_symptom__answer_doctor',
        sceneId: 'describe_symptom',
        slug: 'answer_doctor',
        title: '医師の質問に答える',
        description: '簡単な問診に答える',
        goal: '医師の質問に答えられる',
        difficulty: 4,
        estimatedMinutes: 6,
        isActive: true,
      },
    ],
  },
]

export const MVP_SCENE_IDS: string[] = [
  'wake_up',
  'breakfast',
  'commute',
  'shopping',
  'restaurant',
  'sleep',
  'meet_friend',
  'small_talk',
  'office_greeting',
  'ask_for_help',
  'airport_checkin',
  'hotel_checkin',
  'first_date',
  'text_after_date',
  'express_feelings',
  'describe_symptom',
]
