/**
 * Region Draft — types, normalization, and validation helpers.
 *
 * Regions represent immersion context (landmarks, food, local vibe),
 * NOT accent/dialect reproduction.
 */

// ── Types ──

export type RegionDraft = {
  id: string
  languageCode: string
  countryCode: string
  cityCode: string | null
  displayNameJa: string
  displayNameEn: string
  nativeName: string | null
  aliases: string[]
  landmarkExamples: string[]
  foodExamples: string[]
  placeExamples: string[]
  topicExamples: string[]
  vibeTags: string[]
  politeness: 'casual' | 'neutral' | 'polite'
  slangLevel: 'low' | 'medium' | 'high'
  avoidDialect: boolean
  validation: RegionValidation
}

export type RegionValidation = {
  canonicalMatch: boolean
  aliasConsistency: boolean
  confidence: number
  notes: string[]
}

export type RegionDraftInput = {
  languageCode: string
  countryCode: string
  regionInput: string
}

// ── Normalization ──

/**
 * Normalizes region input text for consistent processing.
 * Handles: full-width → half-width, trim, lowercase latin, katakana/hiragana passthrough.
 */
export function normalizeRegionInput(raw: string): string {
  let s = raw.trim()
  // Full-width alphanumeric → half-width
  s = s.replace(/[\uFF01-\uFF5E]/g, (ch) => String.fromCharCode(ch.charCodeAt(0) - 0xFEE0))
  // Normalize spaces
  s = s.replace(/\u3000/g, ' ').replace(/\s+/g, ' ').trim()
  return s
}

/**
 * Generate a URL-safe slug from a region name.
 * Handles non-Latin scripts (CJK, Arabic, Cyrillic, etc.) by using
 * a hash-based fallback instead of stripping all non-ASCII.
 */
export function safeSlug(input: string): string {
  const normalized = input.trim().toLowerCase()

  // Try Latin-based slugification first
  const latin = normalized
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')

  if (latin.length >= 2) return latin

  // Non-Latin fallback: simple hash from the original string
  let hash = 0
  for (let i = 0; i < normalized.length; i++) {
    hash = ((hash << 5) - hash + normalized.charCodeAt(i)) | 0
  }
  const hex = Math.abs(hash).toString(36).slice(0, 8)
  return `r-${hex}`
}

/** @deprecated Use safeSlug instead */
export const slugify = safeSlug

/**
 * Build minimal alias candidates from the input.
 * Only provides basic normalization variants — multilingual aliases
 * (native script, romanization, etc.) are generated by the AI.
 */
export function buildAliasCandidates(input: string): string[] {
  const normalized = normalizeRegionInput(input)
  const aliases = new Set<string>()
  aliases.add(normalized)
  return [...aliases]
}

// ── Deterministic validation ──

/**
 * Run deterministic validation checks on a draft.
 * AI-based checks are done server-side; this handles what we can check locally.
 */
export function validateDraftDeterministic(draft: RegionDraft): RegionValidation {
  const notes: string[] = []
  let confidence = draft.validation.confidence

  // ── Canonical match: do JA/EN names refer to the same place? ──
  let canonicalMatch = !!(draft.displayNameJa && draft.displayNameEn)
  if (!canonicalMatch) {
    notes.push('Missing Japanese or English display name')
    confidence = Math.min(confidence, 0.3)
  }

  // Reverse-translation check: if nativeName exists, it should appear
  // in aliases or match one of the display names
  if (canonicalMatch && draft.nativeName) {
    const aliasLower = new Set(draft.aliases.map((a) => a.toLowerCase()))
    const nativeLower = draft.nativeName.toLowerCase()
    const enLower = draft.displayNameEn.toLowerCase()
    const jaChars = draft.displayNameJa

    const nativeInAliases = aliasLower.has(nativeLower)
    const nativeMatchesEn = nativeLower === enLower
    const nativeMatchesJa = draft.nativeName === jaChars

    if (!nativeInAliases && !nativeMatchesEn && !nativeMatchesJa) {
      notes.push('Native name not found in aliases or display names — may refer to different place')
      canonicalMatch = false
      confidence = Math.min(confidence, 0.5)
    }
  }

  // ── Alias consistency ──
  const aliasSet = new Set(draft.aliases.map((a) => a.toLowerCase()))
  const aliasConsistency = aliasSet.size >= 2
  if (!aliasConsistency) {
    notes.push('Few aliases — multilingual coverage may be insufficient')
    confidence = Math.min(confidence, 0.6)
  }

  // ── Immersion content check ──
  if (draft.landmarkExamples.length === 0 && draft.foodExamples.length === 0) {
    notes.push('No landmark or food examples')
    confidence = Math.min(confidence, 0.5)
  }

  return {
    canonicalMatch,
    aliasConsistency,
    confidence,
    notes: [...draft.validation.notes, ...notes],
  }
}
